export const LOKIJS_OPTIONS = 'LOKIJS_OPTIONS';
export const LOKIJS_CONST_CLASS_TYPE = 'LOKIJS_CONST_CLASS_TYPE';
export const LOKIJS_CONST_COLLECTION = 'LOKIJS_CONST_COLLECTION';
export const LOKIJS_CONST_COLLECTION_NAME = 'LOKIJS_CONST_COLLECTION_NAME';
export const LOKIJS_CONST_COLLECTION_ENTITY = 'LOKIJS_CONST_COLLECTION_ENTITY';
export const LOKIJS_CONST_COLLECTION_OPTIONS = 'LOKIJS_CONST_COLLECTION_OPTIONS';
export const LOKIJS_CONST_COLLECTION_SUBSCRIBERS = 'LOKIJS_CONST_COLLECTION_SUBSCRIBERS';
export const LOKIJS_CONST_COLLECTION_COLUMNS = 'LOKIJS_CONST_COLLECTION_COLUMNS';

export const LOKIJS_CONST_TOKEN_COLLECTION = (collectionName: string) => `COLLECTION_${collectionName.trim().toUpperCase()}`;
export const LOKIJS_CONST_TOKEN_REPOSITORY = (collectionName: string) => `COLLECTION_${collectionName.trim().toUpperCase()}_REPOSITORY`;